// Note: As of 26/06/2020, local is now named splashtext.js.

var array = [
    "F=ma",
    "Gabriel was here!",
    "In the shadows.",
    "Without a doubt",
    "RUN!!!",
    "Jumping higher than high",
    "y=mx+c or was it b?",
    "Rocket goes vroom!",
    "Wendy's are great.",
    "That will be $9.99.",
    "Objects in water are closer than they appear.",
    "Never trust the girl with blue hair and blue eyes.",
    "Sometimes trust the girl with a strand of blue hair and blue eyes.",
    "Always trust the redhead girl with blue eyes.",
    "Chopping away at the code.",
    "Can't wait for Cyberpunk 2077... in the year 2077.",
    "The internet is internety",
    "They say a man loves pie, because MAH PIE!!!",
    "It was no accident.",
    "Beta Labs is watching.",
    "Alyn loves the snow.",
    "Brought to you by Neuro-Tech.",
    "Test subject #144.",
    "The Immovable Machine.",
    "SAY YES!!!",
    "SAY NO!!!",
    "Today is cold.",
    "A man blind is a man saved.",
    "The robots... are coming...",
    "1999 - Before the martians attacked.",
	"Completed so many things, and its not even noon! - 26/06/2020",
	"The cow actually goes over the earth.",
	"Cyberpunk - Nov 19 (DEALYED AGAIN)",
	"They say I wish too often",
    "Still living it!",
    "This website was made using HTML!",
    "Project Last Hope initiated!",
    "78 89 76 65",
    "71 97 98 114 105 101 108",
    "The past always comes back.",
    "Cracking the code!",
    "Make a Cake! - Jolly Ol' Brits",
    "2 sticks, 3 stone",
    "It's a hard knock life!",
    "1.1.1.1 rocks!",
    "Tor always wins",
    "Getting started",
    "Laura Shigihara, thanks for the memories!",
    "S.I.M.P!",
    "98%",
    "She was adopted!",
    "Time traveling solved!",
    "Scooby Dooby Doooooo!!!",
    "Zoinks!",
    "Error! Not a number!",
    "2012 was the best year!",
    "Thanks Notch!",
    "MEDIC!!!!!!",
    "So anyways, I started blasting!",
    "Don't forget that code!",
    "Gravity set to 20m/s",
    "The earth is flat when viewed on the map.",
	/*
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
	*/
    
]

var num=Math.round(Math.random() * array.length);
document.getElementById("tagline").innerHTML = array[num];