// Note: As of 26/06/2020, local is now named splashtext.js.

var array = [
	"EVA is messed up, cool and sad at the same time",
    "F=ma",
    "Gabriel was here!",
    "In the shadows.",
    "Without a doubt",
    "RUN!!!",
    "Jumping higher than high",
    "y=mx+c or was it b?",
    "Rocket goes vroom!",
    "Wendy's are great.",
    "That will be $9.99.",
    "Objects in water are closer than they appear.",
    "Never trust the girl with blue hair and blue eyes.",
    "Sometimes trust the girl with a strand of blue hair and blue eyes.",
    "Always trust the redhead girl with blue eyes.",
    "Chopping away at the code.",
    "Can't wait for Cyberpunk 2077... in the year 2077.",
    "The internet is internety",
    "They say a man loves pie, because MAH PIE!!!",
    "It was no accident.",
    "Beta Labs is watching.",
    "Alyn loves the snow.",
    "Brought to you by Neuro-Tech.",
    "Test subject #144.",
    "The Immovable Machine.",
    "SAY YES!!!",
    "SAY NO!!!",
    "Today is cold.",
    "A man blind is a man saved.",
    "The robots... are coming...",
    "1999 - Before the martians attacked.",
	"Completed so many things, and its not even noon! - 26/06/2020",
	"The cow actually goes over the earth.",
	"Cyberpunk - Nov 19 (DEALYED AGAIN)",
	"They say I wish too often",
    "Still living it!",
    "This website was made using HTML!",
    "Project Last Hope initiated!",
    "78 89 76 65",
    "71 97 98 114 105 101 108",
    "The past always comes back.",
    "Cracking the code!",
    "Make a Cake! - Jolly Ol' Brits",
    "2 sticks, 3 stone",
    "It's a hard knock life!",
    "1.1.1.1 rocks!",
    "Tor always wins",
    "Getting started",
    "Laura Shigihara, thanks for the memories!",
    "S.I.M.P!",
    "98%",
    "She was adopted!",
    "Time traveling solved!",
    "Scooby Dooby Doooooo!!!",
    "Zoinks!",
    "Error! Not a number!",
    "2012 was the best year!",
    "Thanks Notch!",
    "MEDIC!!!!!!",
    "So anyways, I started blasting!",
    "Don't forget that code!",
    "Gravity set to 20m/s",
    "The earth is flat when viewed on the map.",
    "The favicon is a GIF! Viewable on Firefox!",
    "The Wayback",
	"Don't mention the Wayback",
    "How do you do fellow kids?",
    "Moving houses to the 31st century!",
    "The server hates this",
    "Try Minecraft!",
    "Try Terraria!",
    "Sub to Pewds!",
    "TROLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOL!!!!!!",
    "Hiro Hero!",
    "Baymax!",
    "Locekd and loaded!",
    "Fusion Reaction!",
    "Busses with buoyancy bags",
    "Trains with buoyancy bags",
    "Cars with buoyancy bags",
    "Planes with buoyancy bags",
    "Wireless wired charging is the future",
    "2416",
    "WLP is the future",
    "DUKE KABOOM",
    "Wake the f*ck up Samurai! We have a city to burn.",
    "Protect your healers!",
    "Don't blame it on the healer all the time",
    "Stop locking damage champions!",
    "EVIE IS AWESOME!!!",
    "Maeve mains are cancer",
    "Apple: We now have iAir.",
    "I CANNOT STOP IT!!!",
    "Time to let go!",
    "Hello FBI?",
    "WikiLeaks",
    "Trust LinkedIn? Nope.",
    "Tails!",
    "Security Forces on route!",
    "Vault 7: Athena",
    "Vault 7: Elsa",
    "Vault 7: Brutal Kangaroo",
    "Vault 7: Highrise",
    "Vault 7: Dumbo",
    "Vault 7: CouchPotato",
    "OWCA: Organisation Without a Cool Acronym",
    "@CIA",
    "@ASIO",
    "@FBI",
    "Dipper and Mabel",
    "Gruncle Stan",
    "Phineas and Ferb",
    "Candace",
    "MOM! PHINEAS AND FERB ARE MAKING A NEW MOVIE IN 2020!",
    "Shotgun + Zombies = Satisfication 100%",
    "YouTube Vanced",
    "RIP Mixer.com, you were amazing!",
    "Australia does DNS spoofing with its ISPs. Bypass it with 1.1.1.1.",
    "Happy Evil Song",
	/*
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
	*/
    
]

var num=Math.round(Math.random() * array.length);
document.getElementById("tagline").innerHTML = array[num];