// Note: As of 26/06/2020, local is now named splashtext.js.

/*

A note to anybody reading this, this website is still under development and will take a while.
I will try my best to update it and actually finish the website, but for now it is incomplete by a lot and I'm taking it step by step.

Thank you for your patience.

*/


var array = [
	"Tyln",
	"Tibby",
	"EVA is messed up, cool and sad at the same time",
    "F=ma",
    "Gabriel was here!",
    "In the shadows.",
    "Without a doubt",
    "RUN!!!",
    "Jumping higher than high",
    "y=mx+c or was it b?",
    "Rocket goes vroom!",
    "Wendy's are great.",
    "That will be $9.99.",
    "Objects in water are closer than they appear.",
    "Never trust the girl with blue hair and blue eyes.",
    "Sometimes trust the girl with a strand of blue hair and blue eyes.",
    "Always trust the redhead girl with blue eyes.",
    "Chopping away at the code.",
    "Can't wait for Cyberpunk 2077... in the year 2077.",
    "The internet is internety",
    "They say a man loves pie, because MAH PIE!!!",
    "It was no accident.",
    "Beta Labs is watching.",
    "Alyn loves the snow.",
    "Brought to you by Neuro-Tech.",
    "Test subject #144.",
    "The Immovable Machine.",
    "SAY YES!!!",
    "SAY NO!!!",
    "Today is cold.",
    "A man blind is a man saved.",
    "The robots... are coming...",
    "1999 - Before the martians attacked.",
	"Completed so many things, and its not even noon! - 26/06/2020",
	"The cow actually goes over the earth.",
	"Cyberpunk - Nov 19 (DEALYED AGAIN)",
	"They say I wish too often",
    "Still living it!",
    "This website was made using HTML!",
    "Project Last Hope initiated!",
    "78 89 76 65",
    "71 97 98 114 105 101 108",
    "The past always comes back.",
    "Cracking the code!",
    "Make a Cake! - Jolly Ol' Brits",
    "2 sticks, 3 stone",
    "It's a hard knock life!",
    "1.1.1.1 rocks!",
    "Tor always wins",
    "Getting started",
    "Laura Shigihara, thanks for the memories!",
    "S.I.M.P!",
    "98%",
    "She was adopted!",
    "Time traveling solved!",
    "Scooby Dooby Doooooo!!!",
    "Zoinks!",
    "Error! Not a number!",
    "2012 was the best year!",
    "Thanks Notch!",
    "MEDIC!!!!!!",
    "So anyways, I started blasting!",
    "Don't forget that code!",
    "Gravity set to 20m/s",
    "The earth is flat when viewed on the map.",
    "The favicon is a GIF! Viewable on Firefox!",
    "The Wayback",
	"Don't mention the Wayback",
    "How do you do fellow kids?",
    "Moving houses to the 31st century!",
    "The server hates this",
    "Try Minecraft!",
    "Try Terraria!",
    "Sub to Pewds!",
    "TROLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOL!!!!!!",
    "Hiro the Hero!",
    "Baymax!",
    "Locekd and loaded!",
    "Fusion Reaction!",
    "Busses with buoyancy bags",
    "Trains with buoyancy bags",
    "Cars with buoyancy bags",
    "Planes with buoyancy bags",
    "Wireless wired charging is the future",
    "2416",
    "WLP is the future",
    "DUKE KABOOM",
    "Wake the f*ck up Samurai! We have a city to burn.",
    "Protect your healers!",
    "Don't blame it on the healer all the time",
    "Stop locking damage champions!",
    "EVIE IS AWESOME!!!",
    "Maeve mains are cancer",
    "Apple: We now have iAir.",
    "I CANNOT STOP IT!!!",
    "Time to let go!",
    "Hello FBI?",
    "WikiLeaks",
    "Trust LinkedIn? Nope.",
    "Tails!",
    "Security Forces on route!",
    "Vault 7: Athena",
    "Vault 7: Elsa",
    "Vault 7: Brutal Kangaroo",
    "Vault 7: Highrise",
    "Vault 7: Dumbo",
    "Vault 7: CouchPotato",
    "OWCA: Organisation Without a Cool Acronym",
    "@CIA",
    "@ASIO",
    "@FBI",
    "Dipper and Mabel",
    "Gruncle Stan",
    "Phineas and Ferb",
    "Candace",
    "MOM! PHINEAS AND FERB ARE MAKING A NEW MOVIE IN 2020!",
    "Shotgun + Zombies = Satisfication 100%",
    "YouTube Vanced",
    "RIP Mixer.com, you were amazing!",
    "Australia does DNS spoofing with its ISPs. Bypass it with 1.1.1.1.",
    "Happy Evil Song",
    "I like us better when we're wasted!",
    "Don't feed the ducks",
    "21 Jump Street - HIGH SCHOOL",
    "22 Jump Street - COLLEGE",
    "23 Jump Street - MED SCHOOL",
    "4444444444444444... SCIENCE!",
    "User: COVID-19",
    "...is a Bot",
    "Platyborg",
    "Capture point spawning in 15 seconds!",
    "SAY SOMETHING COOOOOOOOL!!!",
    "{Insert thingy here}",
    "Rooftop Koreans!",
    "Pilot Suit try hards",
    "Oh Ember, you will remember!",
    "Gitchee Gitchee Goo means that I love you!",
    "Build a giant rollercoaster, Robot versions of themselves, Or strand me in a video game, You'd know what I mean if you had seen, The cattle drive, the time machine, The giant Paper Pelican plane, They built motorized chariots, an escalator to the moon, The tallest building, treehouse robots, other nonsense coming soon, A shrinking sub, a waterfall, A robot dog, a Trojan horse, A growth elixir, Perrytronic, Pyramid-related sports!",
    "In This City Of Love",
    "I GAVE UP!",
    "Next Cleanse: 365 Days",
    "Trap of Love - The Hex Girls",
    "The Hex Girls",
    "ITS TRAPPIN TIME!",
    "A-G-L-E-T don't forget it!",
    "Zero to Hero",
    "Is it over yet?",
    "When's the wedding?",
    "The MP5 - The media player choice for the kids located at the back of the classroom. Only available in the US.",
    "Don't eat it dude!",
    "What a SIMP!!!",
    "I always wanted to tell her how I felt. Then COVID happened.",
    "Excuse for introverts: COVID HAPPENED!",
    "When your gf's parents are the same as your ex's...",
    "The Hi-Rez Beta Player (Not sure how)",
    "Adobe is expensive",
    "Burning Rubber 4!",
    "Do you trust me? Probably not anymore then if you did before...",
    "I'm getting too old for this.",
    "Tik Tok is cancer",
    "FOP S10 was bad, 100% no doubt.",
    "UNDO!!! UNDO!!!",
    "You have mail!",
    "#LearnToCode",
    "When you call yourself a journalist but all you post are gifs",
    "Marcy is actually pretty cool!",
    "Why does Anne still not have a shoe after and has sticks and leaves in her hair still?",
    "Sprig is a frog",
    "Corpo",
    "Nomad",
    "Street Kid",
    "Introducing the new eyePhone",
    "Hi_Five",
	"You didn't think my parents actually named me Five did you?"
    "Porky",
    "Miks",
    "404 - Try Again",
    "Glitch Tech's show distorts the blue and red further away from the centre",
    "We're all weirdos, now get back to work",
    "Evert once in a while someone like you appears. The unsung hero, the nameless samarithan. Gian.",
    "Hector Nieves - Service Technician",
    "Stefan Etienne - Still being roasted 2 years later for that PC he built",
    "The Verge PC guy",
    "Ponji Ninja",
    "CynolsIsAway",
    "MOUNTAIN DEW TIME!!!",
	"Commander and Jetsream!",
    "Oh its magic, to watch a planet, shrivel up and die",
    "BRING I.T. ON",
    /*
	"",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
	*/
]

var num=Math.round(Math.random() * array.length);
document.getElementById("tagline").innerHTML = array[num];